# Generated by Django 5.0.2 on 2024-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('prenom', models.TextField()),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('tel', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('place', models.TextField()),
                ('adresse', models.TextField()),
            ],
        ),
    ]
