# Generated by Django 5.0.2 on 2024-02-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('type_transport', models.CharField(max_length=50)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
            ],
        ),
    ]
