# Generated by Django 5.0.2 on 2024-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_flight_hebergement_travelitinerary_delete_voyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
