# Generated by Django 5.0.2 on 2024-03-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_flight_is_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hebergement',
            old_name='date_arrivee',
            new_name='departure_date',
        ),
        migrations.RenameField(
            model_name='hebergement',
            old_name='nombre_personnes',
            new_name='number_of_guests',
        ),
        migrations.RenameField(
            model_name='hebergement',
            old_name='date_depart',
            new_name='return_date',
        ),
    ]
