# Generated by Django 5.0.2 on 2024-03-01 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_date_arrivee_hebergement_departure_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=50)),
                ('activite', models.CharField(max_length=255)),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sejour')),
            ],
        ),
        migrations.DeleteModel(
            name='TravelItinerary',
        ),
    ]
